version: "3.8"

services:
  # IDS Connectors that consists of one Data Provider and one Data Consumer

  dataprovider:
    image: aldidoanta/mendix-ids-connector:latest
    depends_on:
      - db_dataprovider
    environment:
      ADMIN_PASSWORD: Dataprovider1!
      DATABASE_ENDPOINT: postgres://admin:admin@db_dataprovider:5432/db_dp
      MXRUNTIME_ApplicationRootUrl: http://localhost:8081
    ports:
      - 127.0.0.1:8081:8080
    networks:
      - dp
      - ids

  db_dataprovider:
    image: postgres:14.8
    environment:
      - POSTGRES_DB=db_dp
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - db_dataprovider_data:/var/lib/postgresql/data
    networks:
      - dp

  dataconsumer:
    image: aldidoanta/mendix-ids-connector:latest
    depends_on:
      - db_dataconsumer
    environment:
      ADMIN_PASSWORD: Dataconsumer1!
      DATABASE_ENDPOINT: postgres://admin:admin@db_dataconsumer:5432/db_dc
      MX_IDSConnector_VH_Host_Constant: http://vocabularyhub:8000
      MXRUNTIME_ApplicationRootUrl: http://localhost:8082
    ports:
      - 127.0.0.1:8082:8080
    networks:
      - dc
      - ids

  db_dataconsumer:
    image: postgres:14.8
    environment:
      - POSTGRES_DB=db_dc
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - db_dataconsumer_data:/var/lib/postgresql/data
    networks:
      - dc

  # Vocabulary Hub/Interoperability Simulator and the Matchers

  vocabularyhub:
    image: aldidoanta/vocabulary-hub:latest
    depends_on:
      - matchercoma
      - matchercupid
      - matchersimilarityflooding
      - matcherdummy
    env_file:
      - vocabulary_hub/.env
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - vh
      - ids
  
  matchercoma:
    image: aldidoanta/matcher-coma:latest
    env_file:
      - matchers/coma/.env
    ports:
      - "127.0.0.1:8001:8001"
    networks:
      - vh

  matchercupid:
    image: aldidoanta/matcher-cupid:latest
    env_file:
      - matchers/cupid/.env
    ports:
      - "127.0.0.1:8002:8002"
    networks:
      - vh

  matchersimilarityflooding:
    image: aldidoanta/matcher-similarityflooding:latest
    env_file:
      - matchers/similarity_flooding/.env
    ports:
      - "127.0.0.1:8003:8003"
    networks:
      - vh

  matcherdummy:
    image: aldidoanta/matcher-dummy:latest
    ports:
      - "127.0.0.1:8004:8004"
    networks:
      - vh

networks:
  dp:
  dc:
  vh:
  ids:

volumes:
  db_dataprovider_data:
  db_dataconsumer_data:
