version: "3.8"

services:
  dataprovider:
    image: aldidoanta/mendix-ids-connector:1.0
    depends_on:
      - db
    environment:
      ADMIN_PASSWORD: Dataprovider1!
      DATABASE_ENDPOINT: postgres://admin:admin@db:5432/db
    ports:
      - 8080:8080
    networks:
      - ids-logistics

  db:
    image: postgres:14.8
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - ids-logistics
          
networks:
  ids-logistics:

volumes:
  db-data: