version: "3.8"

services:
  dataprovider:
    image: aldidoanta/mendix-ids-connector:latest
    depends_on:
      - db_dataprovider
    environment:
      ADMIN_PASSWORD: Dataprovider1!
      DATABASE_ENDPOINT: postgres://admin:admin@db_dataprovider:5432/db_dp
      MXRUNTIME_ApplicationRootUrl: http://localhost:8081
    ports:
      - 127.0.0.1:8081:8080
    networks:
      - dp
      - ids

  db_dataprovider:
    image: postgres:14.8
    environment:
      - POSTGRES_DB=db_dp
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - db_dataprovider_data:/var/lib/postgresql/data
    networks:
      - dp

networks:
  dp:
  ids:

volumes:
  db_dataprovider_data:
