# Generated by Django 4.2.3 on 2023-08-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Isim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('source_schema', models.CharField(blank=True, default='', max_length=100)),
                ('target_schema', models.CharField(blank=True, default='', max_length=100)),
                ('matcher', models.CharField(choices=[('coma', 'COMA'), ('cupid', 'Cupid')], default=('coma', 'COMA'), max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='PricingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
