openapi: 3.0.3
info:
  title: Matcher - COMA
  version: 1.0.0
  description: API documentation of COMA Matcher
paths:
  /matcher/get-matches:
    post:
      operationId: matcher_get_matches_create
      description: |-
        post:
        Given a source schema and a target schema, returns the schema mapping as the output.
      tags:
      - matcher
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Matcher'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Matcher'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Matcher'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Matcher'
          description: ''
  /matcher/get-matches{format}:
    post:
      operationId: matcher_get_matches_formatted_create
      description: |-
        post:
        Given a source schema and a target schema, returns the schema mapping as the output.
      parameters:
      - in: path
        name: format
        schema:
          type: string
          enum:
          - .json
        required: true
      tags:
      - matcher
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Matcher'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Matcher'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Matcher'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Matcher'
          description: ''
components:
  schemas:
    Matcher:
      type: object
      properties:
        source_schema:
          type: string
          maxLength: 100
        target_schema:
          type: string
          maxLength: 100
      required:
      - source_schema
      - target_schema
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
