# Generated by Django 4.2.3 on 2023-07-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataprovider_schema', models.CharField(blank=True, default='', max_length=100)),
                ('dataconsumer_schema', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
