# Builds a Docker image of Matcher-Dummy and pushes it to Docker Hub, a container registry.

name: Build and push Matcher-Dummy image
on:
  push:
    branches:
      - main
    paths:
      - matchers/dummy/**

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # Checkout a single directory, excluding the root files
          sparse-checkout: matchers/dummy
          sparse-checkout-cone-mode: false
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./matchers/dummy
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/matcher-dummy:latest

